# Generated by Django 3.2.4 on 2023-09-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_Compra',
            fields=[
                ('idActvidadesCliente', models.IntegerField(db_column='idActvidadesCliente', primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='categoria', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Actividades_Compra',
            },
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('idClientes', models.IntegerField(db_column='idClientes', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('Correo_Electronico', models.EmailField(db_column='Correo Electronico', max_length=100)),
                ('Telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('idDireccion', models.IntegerField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('colonia', models.CharField(db_column='colonia', max_length=100)),
                ('ciudad', models.CharField(db_column='ciudad', max_length=100)),
                ('Municipio', models.CharField(db_column='Municipio', max_length=100)),
                ('Estado', models.CharField(db_column='Estado', max_length=100)),
                ('COdigoPostal', models.CharField(db_column='COdigoPostal', max_length=100)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(db_column='idEstado', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='estado', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='EtiquetaCliente',
            fields=[
                ('idEtiquetaCliente', models.IntegerField(db_column='idEtiquetaCliente', primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(db_column='etiqueta', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'EtiquetaCliente',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('idNota', models.IntegerField(db_column='idNota', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('Nota', models.CharField(db_column='categoria', max_length=1000)),
                ('FKidClientes', models.ForeignKey(db_column='FKidClientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'db_table': 'Nota',
            },
        ),
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('idInteCliente', models.IntegerField(db_column='idInteCliente', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('FKEtiquetaCliente', models.ForeignKey(db_column='FKEtiquetaCliente', on_delete=django.db.models.deletion.CASCADE, to='api.etiquetacliente')),
                ('FKidClientes', models.ForeignKey(db_column='FKidClientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'db_table': 'InteraccionCliente',
            },
        ),
        migrations.CreateModel(
            name='Direccion_Clientes',
            fields=[
                ('idDireccion_Clientes', models.IntegerField(db_column='Direccion_Clientes', primary_key=True, serialize=False)),
                ('FKclientes', models.ForeignKey(db_column='FKclientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('FKidDireccion', models.ForeignKey(db_column='FKidDireccion', on_delete=django.db.models.deletion.CASCADE, to='api.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idActividades', models.IntegerField(db_column='idActividades', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('FKActividades_Compra', models.ForeignKey(db_column='Actividades_Compra', on_delete=django.db.models.deletion.CASCADE, to='api.actividades_compra')),
                ('FKEstado', models.ForeignKey(db_column='FKEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('FKclientes', models.ForeignKey(db_column='FKclientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'db_table': 'Compra',
            },
        ),
    ]
